apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: gps-gateway
  name: gps-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: gps-gateway
  template:
    metadata:
      labels:
        app: gps-gateway
        component: gps-gateway
    spec:
      imagePullSecrets:
      - name: aliyun-secret
      containers:
      - name: ccs
        image: registry.cn-beijing.aliyuncs.com/zkkj/${REPO}:${IMAGE_TAG}_ccs
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002
          name: ccs-socket
          protocol: TCP
        resources: {}
        volumeMounts:
          - mountPath: /log
            name: logs
      - name: tcp-monitor
        image: registry.cn-beijing.aliyuncs.com/zkkj/${REPO}:${IMAGE_TAG}_tcp-monitor
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        ports:
        - name: gpstcpser
          containerPort: 3010
          protocol: TCP
        - name: gps
          containerPort: 3001
          protocol: TCP
        - name: gps-udp
          containerPort: 3011
          protocol: UDP
        resources: {}
        volumeMounts:
          - mountPath: /log
            name: logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      serviceAccount: default
      serviceAccountName: default
      volumes:
        - name: logs
          nfs:
            path: /logs/java/test
            server: 192.168.3.240
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gps-gateway
    component: gps-gateway
  name: gps-gateway-tcp
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.0.19
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.19
  ports:
  - name: ccs-socket
    port: 3002
    protocol: TCP
    targetPort: 3002
  - name: gpstcpser
    port: 3010
    protocol: TCP
    targetPort: 3010
  - name: gps
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    component: gps-gateway
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gps-gateway
    component: gps-gateway
  name: gps-gateway-udp
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.0.19
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.19
  ports:
  - name: gps-udp
    port: 3011
    protocol: UDP
    targetPort: 3011
  selector:
    component: gps-gateway
  type: LoadBalancer